name: Validate renovate config
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache: 'npm'
          # To use cache with npx and no package.json
          # https://til.simonwillison.net/github-actions/npm-cache-with-npx-no-package
          cache-dependency-path: '**/.github/workflows/*.yml'
      - name: Validate
        uses: rinchsan/renovate-config-validator@a12a2b98cd4db923c33d1ce407c57afb43f3ff59 # v0.2.0
        with:
          pattern: '*.json' # Regular expression for filename to validate, default to *.json
