name: Validate renovate config
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          cache: 'npm'
          # To use cache with npx and no package.json
          # https://til.simonwillison.net/github-actions/npm-cache-with-npx-no-package
          cache-dependency-path: '**/.github/workflows/*.yml'
      - name: Validate
        uses: rinchsan/renovate-config-validator@a12a2b98cd4db923c33d1ce407c57afb43f3ff59 # v0.2.0
        with:
          pattern: '*.json' # Regular expression for filename to validate, default to *.json
